# aws cloud configuration
cloud:
  token_duration: 129600
  aws_account: "1234567890" # aws account
  aws_user: "aws user" # aws user
  profile: "aws profile to use" # profile of base credentials
  aws_region: "us-east-1" # aws region
  sts_profile: "sts" # sts profile to save in .credentials
# docker repo
docker:
  repository_url: "1234567890.dkr.ecr.us-east-1.amazonaws.com" # ecr repo uri