name: CloudIn CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.12.5
      - name: Run go version
        run: go version

